first workflow for branch3

diff --git a/.github/workflows/account.yml b/.github/workflows/account.yml
--- a/.github/workflows/account.yml
+++ b/.github/workflows/account.yml
@@ -1,21 +1,21 @@
-name: CI Pipeline for account_service
+name: CI Pipeline for customerManagementService
 
 on:
   push:
     branches: 
-      - branch1
+      - branch3
     paths:
-      - 'account_service/**'
+      - 'customerManagementSerive/**'
   pull_request:
     branches:
-      - branch1
+      - branch3
 
 jobs:
   build:
     runs-on: ubuntu-latest
     defaults:
       run:
-        working-directory: ./account_service
+        working-directory: ./customerManagementSerive
 
     steps:
     - name: Checkout code
@@ -23,33 +23,24 @@ jobs:
       with:
         fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
 
-    - name: Set up JDK 17
-      uses: actions/setup-java@v3
+    - name: Setup Node.js
+      uses: actions/setup-node@v3
       with:
-        java-version: '17'
-        distribution: 'temurin'
-        cache: maven
-
+        node-version: 20.11.1 # Adjust based on your project's requirements
+    - name: Install Dependencies
+      run: npm install
     # Make mvnw executable
     - name: Cache SonarQube packages
-      uses: actions/cache@v1
-      with:
-        path: ~/.sonar/cache
-        key: ${{ runner.os }}-sonar
-        restore-keys: ${{ runner.os }}-sonar
-    - name: Cache Maven packages
-      uses: actions/cache@v1
-      with:
-        path: ~/.m2
-        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
-        restore-keys: ${{ runner.os }}-m2
-    - name: Build and analyze
+      uses: sonarsource/sonarqube-scan-action@master
       env:
-        #GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
-      run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=account_service -DskipTests
-
+      # If you wish to fail your job when the Quality Gate is red, uncomment the
+      # following lines. This would typically be used to fail a deployment.
+      # - uses: sonarsource/sonarqube-quality-gate-action@master
+      #   timeout-minutes: 5
+      #   env:
+      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
     # Run SonarQube analysis
     #- name: Run SonarQube analysis
@@ -57,21 +48,21 @@ jobs:
 
     # Set up JDK 17
     
-    - name: Make mvnw executable
-      run: chmod +x ./mvnw
-
+    #- name: Make mvnw executable
+    #  run: chmod +x ./mvnw
+#
     # Build with Maven
-    - name: Build with Maven
-      run: ./mvnw package -DskipTests
-
-    # List target directory contents
-    - name: List target directory contents
-      run: ls -al ./target/
-          
-    # Upload artifact to Nexus
-    - name: Upload artifact to Nexus
-      run: |
-        curl -v -u ${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }} --upload-file ./target/*.jar ${{ secrets.NEXUS_URL }}/repository/maven-releases/com/your-org/account_service/1.0.0/account_service-1.0.0.jar
+    #- name: Build with Maven
+    #  run: ./mvnw package -DskipTests
+#
+    ## List target directory contents
+    #- name: List target directory contents
+    #  run: ls -al ./target/
+    #      
+    ## Upload artifact to Nexus
+    #- name: Upload artifact to Nexus
+    #  run: |
+    #    curl -v -u ${{ secrets.NEXUS_USERNAME }}:${{ secrets.NEXUS_PASSWORD }} --upload-file ./target/*.jar ${{ secrets.NEXUS_URL }}/repository/maven-releases/com/your-org/account_service/1.0.0/account_service-1.0.0.jar
 
     # Log in to Docker Hub
     - name: Log in to Docker Hub
@@ -83,12 +74,12 @@ jobs:
     # Build Docker image
     - name: Build Docker image
       run: |
-        docker build -t ${{ secrets.DOCKER_USERNAME }}/account-service:latest .
+        docker build -t ${{ secrets.DOCKER_USERNAME }}/customer-service:latest .
 
     # Push Docker image to Docker Hub
     - name: Push Docker image to Docker Hub
       run: |
-        docker push ${{ secrets.DOCKER_USERNAME }}/account-service:latest
+        docker push ${{ secrets.DOCKER_USERNAME }}/customer-service:latest
 
 #  aks-login:
 #    runs-on: ubuntu-latest
@@ -128,33 +119,33 @@ jobs:
     
     - name: Apply postgres service
       run: |
-        kubectl apply -f ./account_service/k8s/services/postgres-service.yml
+        kubectl apply -f ./customerManagementService/k8s/services/mysql-service.yml
         sleep 10 # Wait for 1 minute
     - name: Apply account service
       run: |
-        kubectl apply -f ./account_service/k8s/services/account.yml
+        kubectl apply -f ./customerManagementService/k8s/services/customer.yml
         sleep 10 # Wait for 1 minute
-    - name: apply redis service
-      run: |
-        kubectl apply -f ./account_service/k8s/services/redis.yml
-        sleep 10 # Wait for 1 minute
-    - name: Uninstall existing Redis release if it exists
-      run: |
-        helm uninstall redis || echo "Redis not installed previously, skipping uninstall"
-
-    - name: Install Redis using Helm
-      run: |
-        helm repo add bitnami https://charts.bitnami.com/bitnami
-        helm repo update
-        helm install redis bitnami/redis --set auth.enabled=false
-        sleep 10 # Wait for Redis to be deployed
-    - name: Apply pubsub and statestore configurations
-      run: |
-        kubectl apply -f ./account_service/k8s/daprconfig/pubsub.yml
-        kubectl apply -f ./account_service/k8s/daprconfig/subscription.yml
-        kubectl apply -f ./account_service/k8s/daprconfig/staetstore.yml
-        kubectl apply -f ./account_service/k8s/daprconfig/twilio-binding.yml
-        sleep 10 # Wait for 1 minute
+    #- name: apply redis service
+    #  run: |
+    #    kubectl apply -f ./customerManagementService/k8s/services/redis.yml
+    #    sleep 10 # Wait for 1 minute
+    #- name: Uninstall existing Redis release if it exists
+    #  run: |
+    #    helm uninstall redis || echo "Redis not installed previously, skipping uninstall"
+#
+    #- name: Install Redis using Helm
+    #  run: |
+    #    helm repo add bitnami https://charts.bitnami.com/bitnami
+    #    helm repo update
+    #    helm install redis bitnami/redis --set auth.enabled=false
+    #    sleep 10 # Wait for Redis to be deployed
+    #- name: Apply pubsub and statestore configurations
+    #  run: |
+    #    kubectl apply -f ./customerManagementService/k8s/daprconfig/pubsub.yml
+    #    kubectl apply -f ./customerManagementService/k8s/daprconfig/subscription.yml
+    #    kubectl apply -f ./customerManagementService/k8s/daprconfig/staetstore.yml
+    #    kubectl apply -f ./customerManagementService/k8s/daprconfig/twilio-binding.yml
+    #    sleep 10 # Wait for 1 minute
     #- name: Wait for Redis to be ready
     #  run: |
     #    kubectl wait --for=condition=ready pod -l app=redis --timeout=120s
@@ -179,16 +170,16 @@ jobs:
 
     - name: Apply secrets
       run: |
-        kubectl apply -f ./account_service/k8s/secrets/
+        kubectl apply -f ./customerManagementService/k8s/secrets/
         sleep 10 # Wait for 1 minute
 
     - name: Apply configmaps
       run: |
-        kubectl apply -f ./account_service/k8s/configmaps/
+        kubectl apply -f ./customerManagementService/k8s/configmaps/
         sleep 10 # Wait for 1 minute
     - name : Apply pv
       run: |
-        kubectl apply -f ./account_service/k8s/pvc/pv.yml
+        kubectl apply -f ./customerManagementService/k8s/pvc/pv.yml
         sleep 30 # Wait for 1 minut
     #- name: delete all pods and pvc
     #  run: |
@@ -204,17 +195,17 @@ jobs:
 
     - name: Apply persistent volume claims (PVCs)
       run: |
-        kubectl apply -f ./account_service/k8s/pvc/postgres-pvc.yml
+        kubectl apply -f ./customerManagementService/k8s/pvc/mysql-pvc.yml
         sleep 30 # Wait for 1.5 minute
 
     - name: Apply stateful sets
       run: |
-        kubectl apply -f ./account_service/k8s/statefullset/
+        kubectl apply -f ./customerManagementService/k8s/statefullset/
         sleep 30 # Wait for 2 minute
 
     - name: Apply deployments
       run: |
-        kubectl apply -f ./account_service/k8s/deployments/
+        kubectl apply -f ./customerManagementService/k8s/deployments/
 
     #- name: Wait for pods to be healthy
     #  run: |
